# Generated by Django 3.2.9 on 2022-03-08 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField(default=0)),
                ('description', models.TextField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.TextField(default=0)),
                ('description', models.TextField(default=0)),
                ('input', models.TextField(default=0)),
                ('reqornot', models.BooleanField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
            ],
        ),
    ]
