# Generated by Django 3.2.9 on 2022-03-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='input',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='field',
            name='position',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.TextField(default=0),
        ),
    ]
