# Generated by Django 3.2.9 on 2022-03-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220309_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.TextField(default=0),
        ),
    ]
